NationNameData = [
    "Westeros",
    "Azeroth",
    "Arendelle",
    "Arandas",
    "Asamando",
    "Atlantia",
    "Daventry",
    "Delfino",
    "Deltora",
    "Ecotopia",
    "Essos",
    "Genosha",
    "Inazuma",
    "Kalos",
    "Latveria",
    "Númenór",
    "Sothoryos",
    "Themyscira",
    "Valen",
    "Hammerfell",
    "Elsweyr",
    "Skyrim",
    "Summerset",
    "High Rock",
    "Cyrodiil",
    "Morrowind",
    "Eldeen",
    "Breland",
    "Zilargo",
    "Dargun",
    "Valenar",
    "Karrnath",
    "Q'barra",
    "Lhazaar",
    "Aundair",
    "Droaam",
    "Cyre",
    "Australia",
    "Russia",
    "New Zealand",
    "Barbados",
    "Maceadonia",
    "Persia",
    "Egypt",
    "Japan",
    "China",
    "Korea",
    "Ambrosia",
    "Narnia",
    "Avalon",
    "Averna",
    "El Dorado",
    "Elbonia",
    "Freedonia",
    "Laputa",
    "Lilliput",
    "Latveria",
    "Loopaland",
    "Qumar",
    "Shangri-La",
    "Ruritania",
    "Vulgaria",
    "Wakanda",
    "Zembla",
    "Zubrovka",
    "Uqbar",
    "Syldavia",
    "Borduria",
    "San Lorenzo",
    "Naboo",
    "Albion",
    "Eternia",
    "Etheria",
    "Exandria",
    "Hyrule",
    "Krynn",
    "Myst",
    "Nirn",
    "Pern",
    "Spira",
    "Thedas",
    "Tortall",
    "Uresia"
]

NationTitleData = [
    "Republic",
    "Empire",
    "Kingdom",
    "Union",
    "Caliphate",
    "Commonwealth",
    "Principalities",
    "Dominion",
    "Alliance",
    "Collective",
    "Consortium",
    "Wastes",
    "Holds"
]

NationGovTypes = [
    "Monarchy",
    "Magocracy",
    "Theocracy",
    "Democracy",
    "Aristocracy",
    "Anarchy",
    "Dictatorship",
    "Totalitarian",
    "Oligarchy"
]

NationEconomicTypes =[
    "Mining (Precious Metals)",
    "Mining (Non-Precious Metals)",
    "Stone Masonry",
    "Animal Husbandry",
    "Hunting & Trapping",
    "Lumber",
    "Herbalist",
    "Druidic Magic",
    "Agriculture",
    "Trading Caravans",
    "Wool Production",
    "Fishing",
    "Shipbuilding",
    "Pearl Diving",
    "Pirate Economy",
    "Sea Trade",
    "Mariners Guild",
    "Alchemy Ingredients & Herbs",
    "Survivalist Hire",
    "Crafting Services",
    "Trade",
    "Thieves, Spies & Espionage",
    "Technology, Engineering & Artifice",
    "Art & Performance",
    "Mercenaries (Mages)",
    "Mercenaries (Soliders)",
    "Mercenaries (Adventurers)",
    "Mercenaries (Wilderness Guides / Survivalists)",
    "General Magic Services",
    "Rare Artifact Trading",
    "Textiles Production",
    "Fine Crafts",
    "Metalwork",
    "Ale & Beer",
    "Paper",
    "Glass",
    "Precious Stones",
    "Jewelry",
    "Philosophy",
    "Industry",
    "Education",
    "Fashion",
    "Grains",
    "Wine",
    "Spirits",
    "Alchemy",
    "Airship Building",
    "Merchants",
]

NationMilitaryTroopTypes = [
    "Wizards & Sorcerers (Summoning Expertise)",
    "Wizards & Sorcerers (Destruction Expertise)",
    "Wizards & Sorcerers (Teleportation Expertise)",
    "Wizards & Sorcerers (Illusion Expertise)",
    "Wizards & Sorcerers (Shielding & Barrier Expertise)",
    "Wizards & Sorcerers (Arcane Research/Artifacts Expertise)",
    "Adventurers",
    "Assassins",
    "Stealth Operatives (Scouts, Spies)",
    "Mercenaries",
    "Clerics (Healing Expertise)",
    "Clerics (Exorcism Expertise)",
    "Ground Troops (Heavy Infantry)",
    "Ground Troops (Light Infantry)",
    "Ground Troops (Cavalry)",
    "Ground Troops (Siege Weapon Expertise)",
    "Ground Troops (Expertise in Skimishing)",
    "Ground Troops (Ranged Expertise)",
    "Ground Troops (Mage Hunting Expertise)",
    "Ground Troops (Beast Handling Expertise)",
    "Ground Troops (Sappers/Engineers)",
    "Naval Forces (Surface Ships)",
    "Naval Forces (Submersible Vessels)",
    "Naval Forces (Magical/Mystical Entities)",
    "Air Forces (Flying Beasts)",
    "Air Forces (Airships)"
]

NationMilitarySize = [
    "Non-exsistent",
    "Small (Militia)",
    "Moderate",
    "Substantial",
    "Large",
    "World Military Superpower"
]

#Nation Social Tables

NationFamilyTypes = [
    "Nuclear (Traditional Two-parent Household)",
    "Extended (Households with members that span multiple generations)",
    "Collective (community raises the children)",
    "Single Parentage"
]

NationSocialClassTypes = [
    "Caste-based (Strict, hereditary class system)",
    "Feudal System (Nobility, Clery and Commoners)",
    "Meritocracy (Status earned through talents and abilities)",
    "Plutocracy (weath equates to power)",
    "Slave society (society divided into masters and slaves)",
    "Mage Society (society divided into people who can use magic and those who can't)",
    "Technocratic (society divided by those who understand the sciences and those who can't)",
    "Military Rank (society where military Prowess defines status)",
    "Guild Dominace (Society where the Guilds hold the most power)",
    "Purity (social classes determined by the purity of ones Race.)",
]

NationInequalities = [
    "Wealth",
    "Gender",
    "Racial",
    "Religious",
    "Ageism",
    "Access to magic or Technology",
    "Class"
]


#MAybe we use these for Settlements instead.
NationLifeStyles = [
    "Aristocratic",
    "Survivalist",
    "Nomadic",
    "Agrarian",
    "Beastbonded",
    "Religious",
    "Arcane Worship",
    "Aquatic",
    "Underground Dwelling",
    "Treehouse Living (Forest Dwellers)",
    "Airborne (Airship/Avian)",
    "Fey-aligned (Life in Sync with Nature Spirits)",
    "Pirate Living (Sea or Air)",
    "Caste-specific Lifestyles",
    "Mercantile/Trade-focused",
    "Leisure and Pleasure-seeking",
    "Scholarly/Academic (Valuing Knowledge)",
    "Artistic (Valuing Art and Creativity)",
    "Communal (Shared Property and Resources)",
    "Magic-dependent",
    "Technologically Advanced",
    "Ancestral Worship (Life Centered Around Ancestors)",
    "Hero Worship (Life Centered Around Heroes/Champions)",
    "Spartan-like (Militaristic and Austere)",
    "Hedonistic",
    "Isolated/Hermit-like",
    "Warrior Culture (Life Centered Around Combat)",
    "Servitude (Life Centered Around Serving a Higher Power/Class)",
    "Explorer Culture (Emphasizing Discovery and Adventure)",
]