WorldNameData=[
    "Blackmoor",
    "Greyhawk",
    "Mystara",
    "Ravenloft",
    "Pelinore",
    "Dragonlance",
    "Lankhmar",
    "Kara-Tur",
    "Red Sonja",
    "Forgotten Realms",
    "Hollow World",
    "Dark Sun",
    "Thunder Rift",
    "Birthright",
    "Planescape",
    "Jakandor",
    "Rokugan",
    "Middle Earth",
    "Eberron",
    "Mahasarpa",
    "Amethyst",
    "Nentir",
    "Ravnica",
    "Exandria",
    "Theros",
    "Strixhaven",
    "Ashyn",
    "Braize",
    "Lumar",
    "Roshar",
    "Sel",
    "Asgard",
    "Azeroth",
    "Barsoom",
    "Xanth",
    "Taldain",
    "Taladin",
    "Scadrial",
    "Pellucidar",
    "Marithea",
    "Anya",
    "Ceasil",
    "J'nsath",
    "T'athodr",
    "Zeatoc",
    "Fleyl",
    "Surov",
    "Slyntse",
    "Bezluntse",
    "Zrovenai",
    "Hroas",
    "Dyt’bra",
    "Nyrmslu",
    "Yazhir",
    "Jaeze",
    "Hokkaidō",
    "Tōhoku",
    "Akita",
    "Aomori",
    "Fukushima",
    "Iwate",
    "Miyagi",
    "Yamagata",
    "Kantō",
    "Chiba",
    "Gunma",
    "Ibaraki",
    "Kanagawa",
    "Saitama",
    "Tochigi",
    "Tōkyō",
    "Chūbu",
    "Aichi",
    "Fukui",
    "Gifu",
    "Ishikawa",
    "Nagano",
    "Niigata",
    "Moingfielenton",
    "Sious Vale",
    "Davend Pal",
    "Rocks",
    "Leakewaumbrowns",
    "Oakson",
    "Wicott",
    "Akrock",
    "Greville",
    "Ovepert",
    "Siochmon",
    "Atland",
    "Sionia",
    "Fort Spriscon",
    "Pladelarlo",
    "Leach",
    "Gilwary",
    "Sairg",
    "Allend",
    "Stera",
]

def world_name_data():
    return WorldNameData